In [1]:
import numpy as np
import pylab as plt
import numpy.linalg as lin

In [2]:
temperatura = np.genfromtxt('room-temperature.csv',delimiter=',',skip_header=1,usecols=[1,2,3,4])

In [3]:
temperatura_normalizada = (temperatura - np.mean(temperatura,axis=0))/np.std(temperatura,axis = 0)
matriz_covarianza = np.cov(temperatura_normalizada.T)

In [4]:
valores_p, vectores_p = lin.eig(matriz_covarianza)
PC1 = vectores_p[:,0]
PC2 = vectores_p[:,1]
print("PC1 es: [ %.3f" % PC1[0])
for i in range(1,PC1.shape[0]):
      print(", %.3f" % PC1[i])
print(" ] y PC2 es: [ %.3f" % PC2[0])
for i in range(1,PC2.shape[0]):
      print(", %.3f" % PC2[i])

PC1 es: [ -0.494
, -0.5282
, -0.4698
, -0.5063
 ] y PC2 es: [ -0.502
, -0.473
, 0.541
, 0.481


In [5]:
fig1, ax1 = plt.subplots()
colormap = ['yellow','red','green','blue']
etiquetas = ['Frontal izquierdo','Frontal derecho','Posterior izquierdo','Posterior derecho']
for i in range(0,4):
    ax1.scatter(PC1[i],PC2[i], c = colormap[i], s = 10, label = etiquetas[i])
ax1.set_xlabel('Primera componente')
ax1.set_ylabel('Segunda componente')
ax1.legend(etiquetas)
fig1.savefig('Agrupaciones.pdf')
plt.close()

In [6]:
print(valores_p)
print(vectores_p)

[ 8.34471259  1.82614004  0.41382139  0.29663183]
[[-0.49391128 -0.50203076 -0.70984479  0.01171101]
 [-0.52817872 -0.47304176  0.70076399 -0.07866743]
 [-0.46980861  0.54077759 -0.06702403 -0.69451224]
 [-0.50631883  0.48141065  0.02362183  0.71507135]]
