In [1]:
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
def test_zero_in_diagonal(matrix,vector,position):
    for row in range(position+1,len(vector)):
        if(matrix[position][position] == 0):
            stored_row = np.copy(matrix[position])
            stored_entry = np.copy(vector[position])
            matrix[position] = np.copy(matrix[row])
            vector[position] = np.copy(vector[row])
            matrix[row] = np.copy(stored_row)
            vector[row] = np.copy(stored_entry)
    if(matrix[position][position] == 0):
        error = True
    else:
        error = False
        
    return(matrix,vector,error)

In [3]:
def row_echelon_form(matrix,vector):
    non_diagonal = False
    for row in range(len(vector)):
        [matrix,vector,error] = test_zero_in_diagonal(matrix,vector,row)
        if error:
            diag_coeff = 1.0
            non_diagonal = True
        else:
            diag_coeff = matrix[row][row]      
        matrix[row] = matrix[row]/diag_coeff
        vector[row] = vector[row]/diag_coeff        
        for next_row in range(row+1,len(vector)):
            row_coeff = matrix[next_row][row]
            matrix[next_row] = matrix[next_row] - row_coeff*matrix[row]
            vector[next_row] = vector[next_row] - row_coeff*vector[row]    
    return(matrix,vector,non_diagonal)

In [4]:
A = np.array([[4, 8, 3, 1],[0, 4, 0, 1],[9, 1, 2, 4],[7, 7, 7, 1]])
b = np.array([1,1,3,6])
[A,b,Anon_diagonal] = row_echelon_form(A,b)
print(A)
print(b)
print(Anon_diagonal)

[[1 2 0 0]
 [0 1 0 0]
 [0 0 1 2]
 [0 0 0 1]]
[0 0 1 0]
False


In [5]:
B = np.array([[0, 8, 3, 1],[0, 4, 0, 1],[9, 1, 2, 4],[7, 7, 7, 1]])
c = np.array([1,1,3,6])
[B,c,Bnon_diagonal] = row_echelon_form(B,c)
print(B)
print(c)
print(Bnon_diagonal)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[0 0 0 1]
False


In [6]:
C = np.array([[0, 8, 3, 1],[0, 4, 0, 1],[0, 1, 2, 4],[0, 7, 7, 1]])
d = np.array([1,1,3,6])
[C,d,Cnon_diagonal] = row_echelon_form(C,d)
print(C)
print(d)
print(Cnon_diagonal)

[[0 7 7 1]
 [0 1 0 0]
 [0 0 1 2]
 [0 0 0 1]]
[6 0 1 1]
True


In [7]:
def gaussian_elimination(matrix,vector):
    [matrix,vector,non_diagonal] = row_echelon_form(matrix,vector)
    solution = np.zeros(len(vector),np.float64)
    if(not non_diagonal):
        for row in range(len(vector)):
            index = len(vector)-1-row
            solution[index] = vector[index] - np.dot(matrix[index],solution)
    return(solution,non_diagonal)

In [8]:
AA = np.array([[4, 8, 3, 1],[0, 4, 0, 1],[9, 1, 2, 4],[7, 7, 7, 1]],np.float64)
bb = np.array([1,1,3,6],np.float64)
[AAA,bbb,AAAnon_diagonal] = row_echelon_form(AA,bb)
[x,error] = gaussian_elimination(AA,bb)
print(AAA)
print(bbb)
print(x)
print(error)

[[ 1.          2.          0.75        0.25      ]
 [ 0.          1.          0.          0.25      ]
 [ 0.          0.          1.         -1.26315789]
 [ 0.          0.          0.          1.        ]]
[ 0.25        0.25       -1.05263158  2.44262295]
[-1.16393443 -0.36065574  2.03278689  2.44262295]
False


In [9]:
CC = np.array([[0, 8, 3, 1],[0, 4, 0, 1],[0, 1, 2, 4],[0, 7, 7, 1]])
dd = np.array([1,1,3,6])
[CCC,ddd,CCCnon_diagonal] = row_echelon_form(CC,dd)
[y,error2] = gaussian_elimination(CC,dd)
print(CCC)
print(ddd)
print(y)
print(error2)

[[0 0 0 1]
 [0 1 1 0]
 [0 0 1 0]
 [0 0 0 1]]
[1 0 0 0]
[ 0.  0.  0.  0.]
True
