In [1]:
import numpy as np
import numpy.linalg as lin

In [2]:
def PCA_reduction(sample):
    cov_matrix = covariance_matrix(sample)
    [eigenval,eigenvec] = lin.eig(cov_matrix)
    eigenval = np.array([eigenval])
    eigen = np.append(np.transpose(eigenval),np.transpose(eigenvec),axis=1)
    sorted_indexes = eigen[:,0].argsort()
    sorted_indexes = sorted_indexes[::-1]
    eigen_sorted = eigen[sorted_indexes]
    eigenval_sorted = np.transpose(np.array([eigen_sorted[:,0]]))
    eigenvec_sorted = eigen_sorted[:,1:]
    
    weight = 0.0
    n_eigenval = 0
    sum_eigenval = np.sum(eigenval)
    while weight < 0.9:
        weight = weight + eigenval_sorted[n_eigenval]/sum_eigenval
        n_eigenval = n_eigenval + 1
    reduced_indexes = sorted_indexes[0:n_eigenval]+1
    reduced_eigenval = eigenval_sorted[:,0:n_eigenval]
    reduced_eigenvec = eigenvec_sorted[0:n_eigenval,:]
    
    projected_sample = np.dot(reduced_eigenvec,sample)
    return(projected_sample,eigenvec,reduced_indexes)

In [3]:
def covariance_matrix(sample):
    centered_sample = sample-expected_value(sample)
    summ = np.zeros([sample.shape[0],sample.shape[0]])
    for i in range(0,sample.shape[1]):
        x = np.transpose(np.array([centered_sample[:,i]]))
        summ = summ + np.dot(x,np.transpose(x))        
    return summ/(sample.shape[1]-1)    

In [4]:
def expected_value(sample):
    summ = np.transpose(np.array([np.sum(sample,axis=1)]))
    return summ/sample.shape[1]    

In [5]:
sample = np.array([[10,-2,-2,4,9],[-8,0,6,8,-4],[1,2,7,3,4],[2,1,-2,9,-3]])
sample_mean_value = expected_value(sample) 
sample_cov_matrix = covariance_matrix(sample)
[sample_PCAproyection,sample_components,principal_components] = PCA_reduction(sample)

In [6]:
print('El valor medio de la muestra es:\n',sample_mean_value,'\n')
print('La matriz de covarianza de la muestra es:\n',sample_cov_matrix,'\n')
print('La(s) componente(s) es(son):\n',sample_components,'\n')
print('La(s) componente(s) principal(es) de la muestra es(son):\n',principal_components,'\n')
print('La proyeccion de la muestra sobre la(s) componente(s) principal(es) es:\n',sample_PCAproyection)

El valor medio de la muestra es:
 [[ 3.8]
 [ 0.4]
 [ 3.4]
 [ 1.4]] 

La matriz de covarianza de la muestra es:
 [[ 33.2  -25.9   -6.15   1.1 ]
 [-25.9   44.8    8.8   13.3 ]
 [ -6.15   8.8    5.3   -4.7 ]
 [  1.1   13.3   -4.7   22.3 ]] 

La(s) componente(s) es(son):
 [[ 0.58023591 -0.47733905  0.64259504 -0.15015106]
 [-0.77728721 -0.19633447  0.4696069  -0.36979282]
 [-0.14895711  0.22999733  0.49764639  0.82295874]
 [-0.19225675 -0.82504632 -0.34480292  0.40428561]] 

La(s) componente(s) principal(es) de la muestra es(son):
 [1 2] 

La proyeccion de la muestra sobre la(s) componente(s) principal(es) es:
 [[ 11.48718618  -1.65064279  -6.48238138  -6.07453614   8.31221383]
 [ -4.62281006   0.58962644   3.03674526 -10.21545686  -0.11558527]]


In [7]:
sample_temp = np.genfromtxt('room-temperature.csv', delimiter=',', skip_header = 1, usecols = (1,2,3,4))
sample_temp = np.transpose(sample_temp)
sample_temp_mean_value = expected_value(sample_temp) 
sample_temp_cov_matrix = covariance_matrix(sample_temp)
[sample_temp_PCAproyection,sample_temp_components,principal_components_temp] = PCA_reduction(sample_temp)

In [8]:
print('El valor medio de la muestra es:\n',sample_temp_mean_value,'\n')
print('La matriz de covarianza de la muestra es:\n',sample_temp_cov_matrix,'\n')
print('La(s) componente(s) es(son):\n',sample_temp_components,'\n')
print('La(s) componente(s) principal(es) de la muestra es(son):\n',principal_components_temp,'\n')
print('La proyeccion de la muestra sobre la(s) componente(s) principal(es) es:\n',sample_temp_PCAproyection)

El valor medio de la muestra es:
 [[ 294.50763889]
 [ 294.62847222]
 [ 295.0625    ]
 [ 294.97708333]] 

La matriz de covarianza de la muestra es:
 [[ 2.70448669  2.4044663   1.45784091  1.64101544]
 [ 2.4044663   2.94163122  1.60030594  1.80590181]
 [ 1.45784091  1.60030594  2.52082168  2.31242133]
 [ 1.64101544  1.80590181  2.31242133  2.71436626]] 

La(s) componente(s) es(son):
 [[-0.49391128 -0.50203076 -0.70984479  0.01171101]
 [-0.52817872 -0.47304176  0.70076399 -0.07866743]
 [-0.46980861  0.54077759 -0.06702403 -0.69451224]
 [-0.50631883  0.48141065  0.02362183  0.71507135]] 

La(s) componente(s) principal(es) de la muestra es(son):
 [1 2] 

La proyeccion de la muestra sobre la(s) componente(s) principal(es) es:
 [[-591.66334564 -592.02827312 -593.79253149 -592.95674687 -593.78968504
  -593.24863804 -594.87692922 -592.82330749 -594.9829904  -594.6800733
  -593.06340963 -593.17774121 -592.8415019  -590.82540869 -592.49466574
  -590.87553132 -589.87897535 -589.98722252 -589.22733